name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - name: Build
        run: nix-shell --run 'go build ./...'

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - name: Check formatting
        run: |
          nix-shell --run '
            if [ "$(goimports -l . | wc -l)" -gt 0 ]; then
              exit 1
            fi'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - name: Test Go
        run: nix-shell --run 'go test ./...'

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Nix
        uses: cachix/install-nix-action@v13
      - run: nix-shell --run 'make install'
      - name: Terraform fmt
        run: nix-shell --run 'terraform -chdir=./examples fmt -check'
      - name: Terraform init
        run: nix-shell --run 'terraform -chdir=./examples init'
      - name: Terraform validate
        run: nix-shell --run 'terraform -chdir=./examples validate -no-color'
      # TODO: needs hydra running
      # - name: Terraform plan
      #   run: nix-shell --run 'terraform -chdir=./examples plan -no-color'
